<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plausible Plugins API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-rc
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersGoalsCreate
     *
     * Get or create Goal.
     *
     */
    public function testPlausibleWebPluginsAPIControllersGoalsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersGoalsDelete
     *
     * Delete Goal by ID.
     *
     */
    public function testPlausibleWebPluginsAPIControllersGoalsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersGoalsGet
     *
     * Retrieve Goal by ID.
     *
     */
    public function testPlausibleWebPluginsAPIControllersGoalsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersGoalsIndex
     *
     * Retrieve Goals.
     *
     */
    public function testPlausibleWebPluginsAPIControllersGoalsIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersSharedLinksCreate
     *
     * Get or create Shared Link.
     *
     */
    public function testPlausibleWebPluginsAPIControllersSharedLinksCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersSharedLinksGet
     *
     * Retrieve Shared Link by ID.
     *
     */
    public function testPlausibleWebPluginsAPIControllersSharedLinksGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plausibleWebPluginsAPIControllersSharedLinksIndex
     *
     * Retrieve Shared Links.
     *
     */
    public function testPlausibleWebPluginsAPIControllersSharedLinksIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
