<?php
/**
 * Plausible Analytics | Polyfills
 *
 * @since      2.6.2
 * @package    WordPress
 * @subpackage Plausible Analytics
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The bundled Guzzle (src/Client/lib/Lib, generated by Mozart) uses PHP 8.0 functions, e.g. get_debug_type() and
 * preg_last_error_msg(). Upstream, those are provided on PHP 7.x by symfony/polyfill-php80, whose bootstrap.php is
 * normally loaded through Composer's "files" autoloading, which doesn't apply to the libraries Mozart bundles. Mozart
 * does bundle the file itself (pointing it at the prefixed polyfill class), so load it here.
 *
 * It does nothing on PHP 8.0+, and only defines the functions that don't exist yet.
 */
require_once __DIR__ . '/Client/lib/Lib/Symfony/Polyfill/Php80/bootstrap.php';

if ( ! function_exists( 'trigger_deprecation' ) ) {
	/**
	 * The bundled Guzzle reports the use of its deprecated methods, e.g. Utils::jsonEncode() which the generated API
	 * client uses for every request body, through symfony/deprecation-contracts' trigger_deprecation(). Mozart doesn't
	 * bundle that function, so this mirrors it: a silenced E_USER_DEPRECATED, which only surfaces with a custom
	 * error handler.
	 *
	 * @param string $package The name of the package that triggers the deprecation.
	 * @param string $version The version of the package that introduced the deprecation.
	 * @param string $message The message of the deprecation.
	 * @param mixed  ...$args Values to insert in the message using printf() formatting.
	 *
	 * @return void
	 */
	function trigger_deprecation( string $package, string $version, string $message, ...$args ): void {
		// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.DevelopmentFunctions.error_log_trigger_error
		@trigger_error( ( $package || $version ? "Since $package $version: " : '' ) . ( $args ? vsprintf( $message, $args ) : $message ), E_USER_DEPRECATED );
	}
}
